# Use an official Node.js runtime as a parent image
FROM node:18.17.1

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy all project files to the container
COPY . .

# Build the React application
RUN npm run build

# Expose the port your React application will run on (usually 3000)
EXPOSE 3000

# Define the command to start your React application
CMD [ "npm", "start" ]
